### ISSUE TITLE
Feature Request: Defer a function until interrupted

### ISSUE THREAD

**Issue by mattharrigan** [oklog/run#20]
I propose extending go's `defer` where the function would be called when the group is interrupted. Something like:

```go
// Defer a func until interrupted
func (g *Group) Defer(f func()) {
	c := make(chan struct{}, 1)
	execute := func() error {
		<-c
		f()
		return nil
	}
	interrupt := func(error) {
		c <- struct{}{}
	}
	g.Add(execute, interrupt)
}
```
Thanks for a useful package.

**Comment by peterbourgon** [comment]
You can easily do this yourself, as you've demonstrated! :)

**Comment by peterbourgon** [comment]
The 2-method API of a run.Group is it's essential property, I wouldn't grow it for any reason. I'm much more willing to grow the package API by adding helper functions or types, but they would have to have similar ubiquity to SignalHandler — stuff that the majority of consumers would need. 

I can take this admittedly conservative stance because the package is specifically designed to be extensible. The API is basically two function closures, so you don't need special permission or a feature request or etc. to do whatever you want.

**Comment by mattharrigan** [comment]
Thank you
